//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Canvas_AspNetWebForms_WithoutJsSdk.Facebook
{


    public partial class SignedRequest
    {
    }
}
